//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargaPlantillasCierreDeMes.Model.GestionFacturas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelaProvision
    {
        public long IdCancelaProvision { get; set; }
        public string LineItemId { get; set; }
        public short IdSAE { get; set; }
        public string NombreCuenta { get; set; }
        public string RazonSocial { get; set; }
        public string ExpedienteProyecto { get; set; }
        public string ReferenciaElara { get; set; }
        public string EstatusCoS { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<short> Cantidad { get; set; }
        public decimal ImporteUnitario { get; set; }
        public decimal ImporteOriginal { get; set; }
        public string DivisaCotizacion { get; set; }
        public string FormaCobro { get; set; }
        public decimal TipoCambio { get; set; }
        public decimal ImporteMXN { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public short Mes { get; set; }
        public short Anio { get; set; }
        public string SectorCliente { get; set; }
        public string TipoIngreso { get; set; }
        public string KAM { get; set; }
        public string NoFacSae { get; set; }
        public string NombreProyecto { get; set; }
        public Nullable<System.DateTime> FechaDeCierre { get; set; }
        public System.DateTime FG { get; set; }
        public string UG { get; set; }
        public Nullable<System.DateTime> FM { get; set; }
        public string UM { get; set; }
        public Nullable<System.DateTime> FB { get; set; }
        public string UB { get; set; }
        public bool ST { get; set; }
    }
}
