//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargaPlantillasCierreDeMes.Model.GestionFacturas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Elara_GestionFacturasEntities : DbContext
    {
        public Elara_GestionFacturasEntities()
            : base("name=Elara_GestionFacturasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CancelaProvision> CancelaProvision { get; set; }
        public virtual DbSet<Provision> Provision { get; set; }
    }
}
